apiVersion: apps/v1
kind: Deployment
metadata:
  name: h-spring-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: h-spring
  template:
    metadata:
      labels:
        app: h-spring
    spec:
      containers:
      - name: h-spring
        image: begoingto/spring-gradle-app:latest
        ports:
        - containerPort: 8080
