apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h-react-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: h-react-tls
  rules:
  - host: {{.Values.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.appName}}-svc
            port:
              number: 80