apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h-react-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - react-app.example.com
    secretName: h-react-tls
  rules:
  - host: reactjs.begoingtodev.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-svc
            port:
              number: 80